// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ex03.Data;

#nullable disable

namespace ex03.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ex03.Models.Almacen", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("Lugar")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Codigo");

                    b.ToTable("Almacenes");
                });

            modelBuilder.Entity("ex03.Models.Caja", b =>
                {
                    b.Property<string>("NumReferencia")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<int>("AlmacenCodigo")
                        .HasColumnType("int");

                    b.Property<string>("Contenido")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("NumReferencia");

                    b.HasIndex("AlmacenCodigo");

                    b.ToTable("Cajas");
                });

            modelBuilder.Entity("ex03.Models.Caja", b =>
                {
                    b.HasOne("ex03.Models.Almacen", "Almacen")
                        .WithMany("Cajas")
                        .HasForeignKey("AlmacenCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Almacen");
                });

            modelBuilder.Entity("ex03.Models.Almacen", b =>
                {
                    b.Navigation("Cajas");
                });
#pragma warning restore 612, 618
        }
    }
}
